version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: /bin/sh -c "bundle exec guard -ip -l 0.4 & puma"
    env_file: .env
    environment:
      PORT: 2345
      RACK_ENV: development
    ports:
      - "2345:2345"
    volumes:
      - /mnt/github.com/davidkelley/showcase:/app
